auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /loki/wal

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 200
  max_cache_freshness_per_query: 1m
  max_query_parallelism: 32
  max_streams_per_user: 0
  max_global_streams_per_user: 0
  max_line_size: 0
  max_line_size_truncate: false
  max_entries_limit_per_query: 5000

compactor:
  working_directory: /loki/compactor
  retention_enabled: false

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
